handle UnsatisfiedLinkError in LinuxPOSIX constructor, resolves #187
jnr/jnr-posix pull request #188
Opened 2024-02-06 13:21 UTC by betalb

POC PR that will resolve #187

2024-02-06 18:11 UTC, enebo commented
I should add this appears to be written around lazily working but it clearly only worked lazily ONLY is __xstat64 worked.  So at a minimum we could eliminate that one from having volatile field and lazy logic.

2024-02-06 18:55 UTC, headius requested changes
Looks good but we might as well clean up the three booleans and move the whitespace cleanup to a separate commit.

2024-02-06 18:55 UTC, headius commented on src/main/java/jnr/posix/LinuxPOSIX.java
> -	}
We appreciate whitespace cleanup but it should be done as a separate commit to avoid confusing history.

2024-02-06 18:55 UTC, headius commented on src/main/java/jnr/posix/LinuxPOSIX.java
> +            use_xstat64 = false;
As @enebo mentioned, perhaps we should reduce this to a single boolean, since these functions are going to all be present or all not be present.

2024-02-06 19:04 UTC, enebo commented
@betalb could you change this to be a single final boolean for all 3?  Since this happens in the constructor and we try once we can then remove all UnsatisfiedLinkErrors in the 3 stat methods and only check that boolean value.   If you don't want to we can do it but it might be fun to delete code? :smile:

2024-02-07 12:01 UTC, betalb commented
I did the changes, discussed here
Also I mentioned that -1 return code handling was inconsistent between fstat and lstat/stat in versions that accept FileStat object as argument, so I've aligned them.

I can make another change and move error reporting to method versions with 2 arguments (int fd, FileStat stat).

2024-02-07 14:19 UTC, headius commented
@betalb There's definitely an unfortunate lack of consistency in these APIs, as we have been slowly adding and improving them over the past 10-15 years. We would definitely welcome any additional PRs that make things more consistent!

I will review the updated PR.

2024-02-07 14:20 UTC, headius approved these changes
Much cleaner this way! Thank you for making the updates.

2024-02-07 14:20 UTC, merged